name: Go

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build
        run: |
          go build -o service_validator ./cmd
          chmod +x service_validator

      - name: Upload Binary
        uses: actions/upload-artifact@v2
        with:
          name: service_validator
          path: service_validator
